//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Comments { get; set; }
        public string Resolution { get; set; }
        public string Intials { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ShiftTime ShiftTime { get; set; }
        public virtual Type Type { get; set; }
    }
}
